name: Michael Freeborn
title: Michael Freeborn
description: Doctor, programmer, meddler
avatar: https://github.com/mfreeborn/mfreeborn.github.io/blob/master/images/staff_of_python.png?raw=true

footer-links:
  github: mfreeborn
  youtube: channel/UCo3HZI-2tng3k47viP7KDmA

google_analytics: UA-160705019-1
url: mfreeborn.github.io

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

permalink: blog/:year/:month/:day/:title